//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT0301Batch {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BT0301Batch.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ダミーメッセージ００１ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DBG_MSG0020 {
            get {
                return ResourceManager.GetString("DBG_MSG0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DBG_MSG003 {
            get {
                return ResourceManager.GetString("DBG_MSG003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベース操作エラー:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_DB001 {
            get {
                return ResourceManager.GetString("ERR_DB001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーメッセージ登録失敗:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_FailureToEntryErrorMsg {
            get {
                return ResourceManager.GetString("ERR_FailureToEntryErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PUBNO:{0}　ファイル{1}の読み込み失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_FILE_READ {
            get {
                return ResourceManager.GetString("ERR_FILE_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}]ファイルの読み込みが失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_FILE_READ_FAILED {
            get {
                return ResourceManager.GetString("ERR_FILE_READ_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取得対象のファイルが存在しない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_MSG001 {
            get {
                return ResourceManager.GetString("ERR_MSG001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取得対象のフォーマットが想定外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_MSG002 {
            get {
                return ResourceManager.GetString("ERR_MSG002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   二重起動はできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_MULTIPROCESS_PROHIBIT {
            get {
                return ResourceManager.GetString("ERR_MULTIPROCESS_PROHIBIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_NOTEXIST_FILE {
            get {
                return ResourceManager.GetString("ERR_NOTEXIST_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   過去データ取込バッチ - 終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INFO_BATCHEND {
            get {
                return ResourceManager.GetString("INFO_BATCHEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   過去データ取込バッチ - 開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INFO_BATCHSTART {
            get {
                return ResourceManager.GetString("INFO_BATCHSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}のファイルが、変更ないため、データ更新は行われてない。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INFO_NO_MODIFIED_FILE {
            get {
                return ResourceManager.GetString("INFO_NO_MODIFIED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は既に存在しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validate_AlreadyExist {
            get {
                return ResourceManager.GetString("Validate_AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が{1}を上回っています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validate_CompareLargerThan {
            get {
                return ResourceManager.GetString("Validate_CompareLargerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が重複しています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validate_Duplicate {
            get {
                return ResourceManager.GetString("Validate_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validate_Hannyou {
            get {
                return ResourceManager.GetString("Validate_Hannyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validate_MaxLength {
            get {
                return ResourceManager.GetString("Validate_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}:&quot;{1}&quot;はマスタ登録されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validate_NotRegistered {
            get {
                return ResourceManager.GetString("Validate_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードとパスワード確認は一致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validate_PasswdConfirm {
            get {
                return ResourceManager.GetString("Validate_PasswdConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}～{2}の間で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validate_Range {
            get {
                return ResourceManager.GetString("Validate_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字~{2}文字の間で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validate_RangeLength {
            get {
                return ResourceManager.GetString("Validate_RangeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}以上で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validate_RangeMinOnly {
            get {
                return ResourceManager.GetString("Validate_RangeMinOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の形式が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validate_Regx {
            get {
                return ResourceManager.GetString("Validate_Regx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は必須項目です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validate_Required {
            get {
                return ResourceManager.GetString("Validate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}はyyyymmdd形式で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validate_yyyyMMdd {
            get {
                return ResourceManager.GetString("Validate_yyyyMMdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}ファイルが、ファイルサーバーに存在してない。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WAR_NOTFOUNDED_FILE {
            get {
                return ResourceManager.GetString("WAR_NOTFOUNDED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}]のデータが欠損あります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WNG_DATA_LOSS {
            get {
                return ResourceManager.GetString("WNG_DATA_LOSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}][{1}]テーブル更新が失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WNG_DB_FAILED {
            get {
                return ResourceManager.GetString("WNG_DB_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}ファイルのシート「EWD SH」にヘッダーが存在しない。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WNG_NOT_HEADER {
            get {
                return ResourceManager.GetString("WNG_NOT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}ファイルに「EWD SH」シートが存在しない。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WNG_NOT_SHEET {
            get {
                return ResourceManager.GetString("WNG_NOT_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}]は処理対象ファイルではない。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WNG_NotTargetFile {
            get {
                return ResourceManager.GetString("WNG_NotTargetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取得対象のデータに対して他データとの紐づけがうまくいかない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WRN_MSG001 {
            get {
                return ResourceManager.GetString("WRN_MSG001", resourceCulture);
            }
        }
    }
}
